// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Simple greeting command for demonstration purposes. */
	greet: (name: string) => typedError<string, AppError>(__TAURI_INVOKE("greet", { name })),
	/**
	 *  Loads user preferences from disk.
	 *  Returns default preferences if the file doesn't exist.
	 */
	loadPreferences: () => typedError<AppPreferences, AppError>(__TAURI_INVOKE("load_preferences")),
	/**
	 *  Saves user preferences to disk.
	 *  Uses atomic write (temp file + rename) to prevent corruption.
	 */
	savePreferences: (preferences: AppPreferences) => typedError<null, AppError>(__TAURI_INVOKE("save_preferences", { preferences })),
	/**
	 *  Sends a native system notification.
	 *  On mobile platforms, returns an error as notifications are not yet supported.
	 */
	sendNativeNotification: (title: string, body: string | null) => typedError<null, AppError>(__TAURI_INVOKE("send_native_notification", { title, body })),
	/**
	 *  Saves emergency data to a JSON file for later recovery.
	 *  Validates filename and enforces a 10MB size limit.
	 * 
	 *  Accepts a JSON string (not a parsed value) to avoid a recursive-type
	 *  stack overflow in tauri-specta's TypeScript codegen.
	 */
	saveEmergencyData: (filename: string, data: string) => typedError<null, RecoveryError>(__TAURI_INVOKE("save_emergency_data", { filename, data })),
	/**
	 *  Loads emergency data from a previously saved JSON file.
	 *  Returns FileNotFound if the file doesn't exist.
	 * 
	 *  Returns a JSON string (not a parsed value) to avoid a recursive-type
	 *  stack overflow in tauri-specta's TypeScript codegen.
	 */
	loadEmergencyData: (filename: string) => typedError<string, RecoveryError>(__TAURI_INVOKE("load_emergency_data", { filename })),
	/**
	 *  Removes recovery files older than 7 days.
	 *  Returns the count of removed files.
	 */
	cleanupOldRecoveryFiles: () => typedError<number, RecoveryError>(__TAURI_INVOKE("cleanup_old_recovery_files")),
	/**  Shows the quick pane window and makes it the key window (for keyboard input). */
	showQuickPane: () => typedError<null, AppError>(__TAURI_INVOKE("show_quick_pane")),
	/**
	 *  Dismisses the quick pane window.
	 *  On macOS, resigns key window status before hiding to avoid activating main window.
	 */
	dismissQuickPane: () => typedError<null, AppError>(__TAURI_INVOKE("dismiss_quick_pane")),
	/**  Toggles the quick pane window visibility. */
	toggleQuickPane: () => typedError<null, AppError>(__TAURI_INVOKE("toggle_quick_pane")),
	/**  Returns the default shortcut constant for frontend use. */
	getDefaultQuickPaneShortcut: () => __TAURI_INVOKE<string>("get_default_quick_pane_shortcut"),
	/**
	 *  Updates the global shortcut for the quick pane.
	 *  Pass None to reset to default.
	 */
	updateQuickPaneShortcut: (shortcut: string | null) => typedError<null, AppError>(__TAURI_INVOKE("update_quick_pane_shortcut", { shortcut })),
	/**
	 *  Update the tray icon state (Normal / Notification badge).
	 * 
	 *  Exposed as a Tauri command so the frontend can trigger a badge
	 *  (e.g. when a notification arrives or unread count changes).
	 */
	setTrayIconState: (state: TrayIconState) => typedError<null, AppError>(__TAURI_INVOKE("set_tray_icon_state", { state })),
	/**
	 *  Move a window to a tray-relative position (e.g. for popover-style panels).
	 * 
	 *  Exposed as a Tauri command so the frontend can position the quick pane
	 *  or a popover relative to the tray icon.
	 */
	moveWindowToTray: (windowLabel: string, position: TrayPosition) => typedError<null, AppError>(__TAURI_INVOKE("move_window_to_tray", { windowLabel, position })),
	/**
	 *  Reads the crash report file if it exists.
	 *  Returns None if no crash file is found.
	 */
	readCrashReport: () => typedError<{
	/**  Type of crash (e.g., "rust_panic") */
	crash_type: string,
	/**  Panic message */
	message: string,
	/**  Source location (file:line:column), if available */
	location: string | null,
	/**  Full backtrace string */
	backtrace: string,
	/**  Unix timestamp (seconds since epoch) */
	timestamp: number | null,
	/**  Application version when the crash occurred */
	app_version: string,
} | null, AppError>(__TAURI_INVOKE("read_crash_report")),
	/**
	 *  Deletes the crash report file.
	 *  Called after the crash has been sent to Sentry or dismissed by the user.
	 */
	deleteCrashReport: () => typedError<null, AppError>(__TAURI_INVOKE("delete_crash_report")),
	/**
	 *  Sets the crash reporting consent state.
	 * 
	 *  Called by the frontend when the user grants or denies consent via the
	 *  preferences pane or the crash report dialog. The state is stored both
	 *  in-memory (via `CONSENT_STATE`) **and** persisted to `preferences.json`
	 *  on the Rust side, so it survives restarts even if the frontend doesn't
	 *  call `save_preferences`.
	 */
	setConsent: (consent: boolean | null) => typedError<null, AppError>(__TAURI_INVOKE("set_consent", { consent })),
};

/* Types */
/**
 *  The unified error type used by all Tauri command handlers.
 * 
 *  Each variant corresponds to a broad category of failure. The `kind` tag
 *  allows the frontend to switch on error type, while the `message` field
 *  carries human-readable details.
 */
export type AppError = 
/**  File system or I/O error. */
{ kind: "Io"; message: string } | 
/**  JSON (de)serialization error. */
{ kind: "Serialization"; message: string } | 
/**  Path resolution error (e.g. app data dir not found). */
{ kind: "Path"; message: string } | 
/**  Input validation error. */
{ kind: "Validation"; message: string } | 
/**  Resource not found. */
{ kind: "NotFound"; message: string } | 
/**  Task join error from `spawn_blocking`. */
{ kind: "TaskJoin"; message: string } | 
/**  Tray icon operation error. */
{ kind: "Tray"; message: string } | 
/**  Quick pane operation error. */
{ kind: "QuickPane"; message: string } | 
/**  Notification error. */
{ kind: "Notification"; message: string } | 
/**  Window operation error. */
{ kind: "Window"; message: string };

/**
 *  Application preferences that persist to disk.
 *  Only contains settings that should be saved between sessions.
 */
export type AppPreferences = {
	theme?: string,
	/**
	 *  Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
	 *  If None, uses the default shortcut
	 */
	quick_pane_shortcut: string | null,
	/**
	 *  User's preferred language (e.g., "en", "es", "de")
	 *  If None, uses system locale detection
	 */
	language: string | null,
	/**  Crash reporting consent: None = not asked, Some(true) = consent, Some(false) = denied */
	crash_reporting_consent: boolean | null,
};

/**
 *  Crash report data captured by the panic hook and stored to disk.
 *  The frontend reads this on next startup and sends it to Sentry (if consent given).
 */
export type CrashReportData = {
	/**  Type of crash (e.g., "rust_panic") */
	crash_type: string,
	/**  Panic message */
	message: string,
	/**  Source location (file:line:column), if available */
	location: string | null,
	/**  Full backtrace string */
	backtrace: string,
	/**  Unix timestamp (seconds since epoch) */
	timestamp: number | null,
	/**  Application version when the crash occurred */
	app_version: string,
};

/**  Error types for recovery operations (typed for frontend matching) */
export type RecoveryError = 
/**  File does not exist (expected case, not a failure) */
{ kind: "FileNotFound" } | 
/**  Filename validation failed */
{ kind: "ValidationError"; message: string } | 
/**  Data exceeds size limit */
{ kind: "DataTooLarge"; max_bytes: number } | 
/**  File system read/write error */
{ kind: "IoError"; message: string } | 
/**  JSON serialization/deserialization error */
{ kind: "ParseError"; message: string };

/**  Tray icon states — controls which icon is displayed. */
export type TrayIconState = 
/**  Default app icon */
"Normal" | 
/**  Icon with a notification badge (e.g. unread items) */
"Notification";

/**  Tray window position — controls where the window appears relative to the tray icon. */
export type TrayPosition = 
/**  Top-left of tray icon */
"TopLeft" | 
/**  Top-right of tray icon */
"TopRight" | 
/**  Bottom-left of tray icon */
"BottomLeft" | 
/**  Bottom-right of tray icon */
"BottomRight";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

