import { defineConfig } from 'vitest/config'
import path from 'path'

// Separate Vitest config — keeps test runner independent of Vite build plugins
// (Sentry Vite plugin, Rolldown Babel, Tailwind CSS) that only apply to builds.
export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      // Workaround: Vite's package exports resolver fails on non-ASCII paths.
      // Map the subpath export directly to the physical file.
      '@testing-library/jest-dom/vitest': path.resolve(
        __dirname,
        'node_modules/@testing-library/jest-dom/dist/vitest.mjs'
      ),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules', 'dist', 'e2e', 'playwright-report', 'test-results'],
    maxWorkers: 4,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/**/*.spec.{ts,tsx}',
        'src/test/**',
        'src/main.tsx',
        'src/quick-pane-main.tsx',
        'src/vite-env.d.ts',
        // Auto-generated by tauri-specta — cannot be hand-tested
        'src/lib/bindings.ts',
        // shadcn/ui wrapper components over Radix UI primitives — tested upstream
        'src/components/ui/**',
      ],
      // 覆盖率阈值对齐「核心域分支≥80%」标准。当前全量实际：语句 ~97%、
      // 分支 ~93%、函数 ~96%、行 ~97%，远超阈值，为未来演进保留余量。
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
  },
})
