use tauri_specta::{Builder, collect_commands};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{crash_report, notifications, preferences, quick_pane, recovery, tray};

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        tray::set_tray_icon_state,
        tray::move_window_to_tray,
        crash_report::read_crash_report,
        crash_report::delete_crash_report,
        crash_report::set_consent,
    ])
}

/// Exports TypeScript bindings to `src/lib/bindings.ts`.
///
/// Runs in a dedicated thread with an enlarged stack to avoid the
/// `STATUS_STACK_OVERFLOW` (0xC00000FD) crash that tauri-specta can
/// trigger on Windows when serialising many command signatures.
#[allow(dead_code)] // only called by `cargo test export_bindings -- --ignored`
pub fn export_ts_bindings() {
    std::thread::Builder::new()
        .stack_size(32 * 1024 * 1024) // 32 MB — specta type graph recursion is very deep
        .spawn(|| {
            generate_bindings()
                .export(
                    specta_typescript::Typescript::default().header(
                        "// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n",
                    ),
                    "../src/lib/bindings.ts",
                )
                .expect("Failed to export TypeScript bindings");
        })
        .expect("Failed to spawn bindings-export thread")
        .join()
        .expect("Bindings-export thread panicked");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
